on:
  workflow_dispatch:

jobs:
  netcdf-java-build:
    name: netCDF-Java Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 8, 11, 14 of zulu and temurin java
        java-version: [ 8, 11, 14 ]
        java-vendor: [ 'zulu', 'temurin' ]
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle (${{ matrix.java-vendor }} ${{ matrix.java-version }})
        uses: Unidata/thredds-test-action@v2
        with:
          java-vendor: ${{ matrix.java-vendor }}
          java-version: ${{ matrix.java-version }}
          build-tool: 'gradlew'
          test-command: 'build -x test'
